# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "app01_machine" do |app|
        app.vm.box = "ubuntu/jammy64"
        app.vm.network "private_network", ip: "192.168.56.10"
        app.vm.network "forwarded_port", guest: 80, host: 8001
        # app.vm.network "private_network", ip: "172.16.238.10"
        app.vm.hostname = "app01"
        #app.vm.synced_folder "./app", "/app", disabled: true
        app.vm.provider "virtualbox" do |vb|
           vb.gui = false
           vb.name = "app01"
           vb.memory = "2048"
        end

        app.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get -y install python3.10-venv
        SHELL
    end

    config.vm.define "db01_machine" do |db|
        db.vm.box = "ubuntu/jammy64"
        db.vm.network "private_network", ip: "192.168.56.11"
        db.vm.hostname = "db01"
        db.vm.provider "virtualbox" do |vb|
            vb.gui = false         
            vb.memory = "2048"
        end

        db.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y postgresql postgresql-contrib
        SHELL
    end

    config.vm.define "backup_machine" do |backup|
        backup.vm.box = "ubuntu/jammy64"
        backup.vm.network "private_network", ip: "192.168.56.12"
        backup.vm.hostname = "backup01"
        backup.vm.provider "virtualbox" do |vb|
            vb.gui = false         
            vb.memory = "1024"
        end

        # config.vm.provision "shell", inline: <<-SHELL
        #   apt-get update
        #   apt-get upgrade
        #   apt-get install vsftpd
        #   apt-get update
        # SHELL
    end

  end
  
# J'ai eu un probleme quand j'ai donné les adresses 172.16, le range d'adresse IP était sur du 192.168
# vagrant status
# vagrant up app01